"""
ScholarOS AI Embeddings.

Provides strongly typed embedding requests, responses, and interfaces
for vector generation and knowledge indexing.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Protocol


@dataclass(slots=True)
class EmbeddingRequest:
    """
    Request to generate dense vector embeddings for text inputs.
    """

    input: list[str]
    model: str | None = None
    dimensions: int | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_text(cls, text: str, model: str | None = None, **kwargs: Any) -> EmbeddingRequest:
        """Create a request for a single string input."""
        return cls(input=[text], model=model, **kwargs)

    @classmethod
    def from_texts(cls, texts: list[str], model: str | None = None, **kwargs: Any) -> EmbeddingRequest:
        """Create a request for multiple string inputs."""
        return cls(input=list(texts), model=model, **kwargs)


@dataclass(slots=True, frozen=True)
class EmbeddingResponse:
    """
    Vector embeddings generated by an embedding model.
    """

    embeddings: list[list[float]]
    model: str
    dimensions: int
    tokens_used: int = 0
    latency_ms: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def vector(self) -> list[float]:
        """Return the first embedding vector."""
        if not self.embeddings:
            return []
        return self.embeddings[0]

    @property
    def count(self) -> int:
        """Return the number of generated vectors."""
        return len(self.embeddings)

    @staticmethod
    def cosine_similarity(vec1: list[float], vec2: list[float]) -> float:
        """Calculate cosine similarity between two float vectors."""
        if len(vec1) != len(vec2) or not vec1:
            return 0.0

        dot = sum(a * b for a, b in zip(vec1, vec2))
        norm1 = math.sqrt(sum(a * a for a in vec1))
        norm2 = math.sqrt(sum(b * b for b in vec2))

        if norm1 == 0.0 or norm2 == 0.0:
            return 0.0

        return dot / (norm1 * norm2)


class EmbeddingProvider(Protocol):
    """Protocol for providers that support vector embeddings."""

    def embed(self, request: EmbeddingRequest) -> EmbeddingResponse:
        """Generate embeddings for the given request."""
        ...


__all__ = [
    "EmbeddingProvider",
    "EmbeddingRequest",
    "EmbeddingResponse",
]
