"""
ScholarOS
Application Controller

Version : 1.0
Status  : In Development
Python  : 3.14+

Description
-----------
Coordinates the application.

The controller acts as the central
orchestrator between the GUI and the
backend services.

Business logic does not belong inside
the GUI.

Future responsibilities include:

• Chat requests
• Research execution
• RAG retrieval
• Plugin dispatch
• Workspace management
• Session lifecycle
"""

from __future__ import annotations


from scholaros.gui.window import GUIWindow


class ApplicationController:
    """
    Coordinates ScholarOS.

    The controller owns the GUI and
    receives events generated by it.

    Backend systems will later be attached
    here without modifying the GUI layer.
    """

    def __init__(
        self,
        window: GUIWindow,
    ) -> None:
        """
        Initialize the controller.

        Parameters
        ----------
        window:
            Main application window.
        """

        self._window = window

    # ---------------------------------------------------------
    # Properties
    # ---------------------------------------------------------

    @property
    def window(
        self,
    ) -> GUIWindow:
        """
        Return the GUI window.
        """

        return self._window

    # ---------------------------------------------------------
    # Lifecycle
    # ---------------------------------------------------------

    def initialize(
        self,
    ) -> None:
        """
        Prepare the application.

        Future startup tasks:

        • load configuration
        • initialize services
        • register plugins
        • restore session
        """

        self.window.build()

    def run(
        self,
    ) -> None:
        """
        Start ScholarOS.
        """

        self.initialize()

        self.window.show()

    # ---------------------------------------------------------
    # Navigation
    # ---------------------------------------------------------

    def show_home(
        self,
    ) -> None:
        """
        Display the home page.
        """

        self.window.show_welcome()

    def show_chat(
        self,
    ) -> None:
        """
        Display the chat workspace.
        """

        self.window.show_chat()

    def show_research(
        self,
    ) -> None:
        """
        Display the research workspace.
        """
        if hasattr(self.window, "show_research") and callable(self.window.show_research):
            self.window.show_research()

    def show_library(
        self,
    ) -> None:
        """
        Display the library workspace.
        """
        if hasattr(self.window, "show_library") and callable(self.window.show_library):
            self.window.show_library()

    def show_plugins(
        self,
    ) -> None:
        """
        Display the plugins workspace.
        """
        if hasattr(self.window, "show_plugins") and callable(self.window.show_plugins):
            self.window.show_plugins()

    def show_settings(
        self,
    ) -> None:
        """
        Display the settings workspace.
        """
        if hasattr(self.window, "show_settings") and callable(self.window.show_settings):
            self.window.show_settings()

    # ---------------------------------------------------------
    # Events
    # ---------------------------------------------------------

    def on_chat_submit(
        self,
        prompt: str,
    ) -> None:
        """
        Handle a submitted prompt.

        AI integration will be connected
        here in future milestones.
        """

        del prompt

    def on_exit_requested(
        self,
    ) -> None:
        """
        Handle application shutdown.
        """

        self.window.root.destroy()

    # ---------------------------------------------------------

    def __repr__(
        self,
    ) -> str:
        """
        Return a developer-friendly
        representation.
        """

        return (
            f"{self.__class__.__name__}("
            f"window={self.window!r}"
            f")"
        )